"""Place authorized source PNGs beside the evidence that mentions them.

Canonical answers/cache entries never contain bearer links. URLs are issued at
delivery time, after fresh authorization, and are never generated by the LLM.
"""
from __future__ import annotations

from html import escape
import re

from src.citations import _MARKER


def image_markdown(ref, url):
    label = ref.get("caption") or ref.get("filename") or "Source diagram"
    if ref.get("page") is not None:
        label += f" — page {ref['page']}"
    elif ref.get("slide") is not None:
        label += f" — slide {ref['slide']}"
    label = " ".join(str(label).split())[:300]
    label = re.sub(r"([\\`*_{}\[\]!|])", r"\\\1", escape(label, quote=False))
    return f"![{label}]({url})"


def inline_images(answer, images, *, url_field="inline_url"):
    """Insert once after the first prose block citing each selected figure.

Code, existing links and unreferenced figures never become placement anchors.
This works with canonical evidence IDs before display citation formatting.
"""
    if not answer or not images:
        return answer
    occurrences = {}
    for match in _MARKER.finditer(answer):
        if match.group("id"):
            occurrences.setdefault(match["id"], match.end())
    insertions, seen = {}, set()
    for ref in images:
        url = ref.get(url_field)
        key = (ref.get("doc_id"), ref.get("figure_id"))
        if not url or key in seen:
            continue
        ids = ref.get("evidence_ids") or [ref.get("evidence_id", "")]
        anchors = [occurrences[eid] for eid in ids if eid in occurrences]
        if not anchors:
            continue
        seen.add(key)
        anchor = min(anchors)
        boundary = re.search(r"\n[ \t]*\n", answer[anchor:])
        end = anchor + boundary.start() if boundary else len(answer)
        insertions.setdefault(end, []).append(image_markdown(ref, url))
    for end in sorted(insertions, reverse=True):
        answer = answer[:end] + "\n\n" + "\n\n".join(insertions[end]) + answer[end:]
    return answer


async def public_images(images, groups, metadata_store):
    """Reauthorize references and attach fresh capabilities when configured."""
    from src.figures.service import authorized_figure, reference
    from src.figures.links import issue_short
    result = []
    for ref in images:
        try:
            doc, figure = await authorized_figure(ref["doc_id"], ref["figure_id"], groups, metadata_store)
            current = reference(doc, figure, ref.get("relevance"), ref.get("variant", "preview"))
            if current is not None:
                if ((ref.get("sha256") and ref["sha256"] != current["sha256"])
                        or (ref.get("source_revision") and ref["source_revision"] != current["source_revision"])):
                    continue  # Never illustrate an old answer with a replacement image.
                current.update({"evidence_id": ref.get("evidence_id", ""),
                                "evidence_ids": ref.get("evidence_ids") or [ref.get("evidence_id", "")]})
                current.update(await issue_short(doc, current, metadata_store) or {})
                result.append(current)
        except (OSError, ValueError):
            continue
    return result


async def present_answer(answer, images, groups, metadata_store):
    images = await public_images(images, groups, metadata_store)
    return inline_images(answer, images), images
